import { defineConfig } from 'vitepress';

export default defineConfig({
  lang: 'zh-CN',
  title: 'gis-sdk',
  description: '框架无关、可扩展的 Cesium GIS SDK',
  appearance: 'dark',
  cleanUrls: true,
  srcExclude: [
    'superpowers/**',
    'research/**',
    'api-readme.md',
    'cesium-sdk-prd.md',
    'publishing.md',
  ],
  lastUpdated: true,
  themeConfig: {
    nav: [
      { text: '快速开始', link: '/guide/getting-started' },
      { text: 'API 使用', link: '/guide/api-reference' },
      { text: '功能状态', link: '/guide/capability-status' },
      { text: '类型索引', link: '/api/' },
      { text: '变更日志', link: '/changelog' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: '开始',
          items: [
            { text: '快速开始', link: '/guide/getting-started' },
            { text: '导入与包体积', link: '/guide/imports' },
            { text: 'API 使用参考', link: '/guide/api-reference' },
          ],
        },
        {
          text: '地图运行',
          items: [
            { text: '地图生命周期', link: '/guide/map-lifecycle' },
            { text: '地图控制', link: '/guide/map-controls' },
            { text: '外部接入点（瓦片 / 地形 / 数据地址）', link: '/guide/external-endpoints' },
            { text: '2D / 3D 场景切换', link: '/guide/scene-mode' },
            { text: '坐标转换', link: '/guide/coordinates' },
            { text: '渲染质量与自动降档', link: '/guide/quality' },
            { text: '拾取交互', link: '/guide/picking' },
            { text: '绘制与顶点编辑', link: '/guide/drawing' },
            { text: '环境效果', link: '/guide/environment' },
            { text: '空间闪电 map.lightning', link: '/guide/lightning' },
            { text: '画布快照', link: '/guide/capture' },
            { text: '空间计算与坐标转换', link: '/guide/spatial-analysis' },
            { text: '分析工具 map.analysis', link: '/guide/analysis' },
            { text: 'Worker 内执行分析', link: '/guide/analysis-worker' },
            { text: '轨道与姿态数学', link: '/guide/orbit-math' },
            { text: 'CZML 生成与解析', link: '/guide/czml' },
          ],
        },
        {
          text: '图层与覆盖物',
          items: [
            { text: '图层使用导航', link: '/guide/layers' },
            { text: '图层管理', link: '/guide/layer-management' },
            { text: 'GeoJSON 图层', link: '/guide/geojson-layer' },
            { text: 'WMS、TMS、WMTS 与单图影像', link: '/guide/imagery-layers' },
            { text: '密度热力图', link: '/guide/heatmap-layer' },
            { text: '3D Tiles 图层', link: '/guide/tiles3d-layer' },
            { text: '静态模型图层', link: '/guide/model-layer' },
            { text: '点位图层与 CSV 导入', link: '/guide/points-layer' },
            { text: '点位导入计划', link: '/guide/point-import' },
            { text: '折线图层与内置材质', link: '/guide/polyline-layer' },
          ],
        },
        {
          text: '实时数据',
          items: [
            { text: '实时数据导航', link: '/guide/data-pipeline' },
            { text: '有界数据管线', link: '/guide/data-pipeline-core' },
            { text: 'Worker / MessagePort 输入', link: '/guide/data-pipeline-message-input' },
            { text: '帧预算调度', link: '/guide/data-pipeline-frame-scheduler' },
            { text: '实时链路（WebSocket）', link: '/guide/realtime-socket' },
            { text: '实时链路组装（从数据到画面）', link: '/guide/realtime-cookbook' },
            { text: '实时水位线与时间戳守卫', link: '/guide/realtime-waterline' },
            { text: '会话门禁与重同步', link: '/guide/realtime-session' },
            { text: '位置批量归一化', link: '/guide/position-batch' },
            { text: '仿真 / 回放时钟', link: '/guide/simulation-clock' },
            { text: '回放时间轴', link: '/guide/replay-timeline' },
            { text: '仿真事件调度', link: '/guide/simulation-events' },
          ],
        },
        {
          text: '可靠性与参考',
          items: [
            { text: '诊断快照', link: '/guide/diagnostics' },
            { text: '性能基准（计算与渲染）', link: '/guide/performance' },
            { text: '错误与原生出口', link: '/guide/errors-and-native' },
            { text: '功能状态与路线图', link: '/guide/capability-status' },
            { text: 'TypeScript 类型索引', link: '/api/' },
            { text: '变更日志', link: '/changelog' },
          ],
        },
      ],
      '/': [
        {
          text: 'gis-sdk',
          items: [
            { text: '概览', link: '/' },
            { text: '快速开始', link: '/guide/getting-started' },
            { text: 'API 使用参考', link: '/guide/api-reference' },
            { text: '地图生命周期', link: '/guide/map-lifecycle' },
            { text: '地图控制', link: '/guide/map-controls' },
            { text: '外部接入点（瓦片 / 地形 / 数据地址）', link: '/guide/external-endpoints' },
            { text: '2D / 3D 场景切换', link: '/guide/scene-mode' },
            { text: '坐标转换', link: '/guide/coordinates' },
            { text: '渲染质量与自动降档', link: '/guide/quality' },
            { text: '拾取交互', link: '/guide/picking' },
            { text: '绘制与顶点编辑', link: '/guide/drawing' },
            { text: '环境效果', link: '/guide/environment' },
            { text: '空间闪电 map.lightning', link: '/guide/lightning' },
            { text: '画布快照', link: '/guide/capture' },
            { text: '空间计算与坐标转换', link: '/guide/spatial-analysis' },
            { text: '分析工具 map.analysis', link: '/guide/analysis' },
            { text: 'Worker 内执行分析', link: '/guide/analysis-worker' },
            { text: '轨道与姿态数学', link: '/guide/orbit-math' },
            { text: 'CZML 生成与解析', link: '/guide/czml' },
            { text: '图层使用导航', link: '/guide/layers' },
            { text: '图层管理', link: '/guide/layer-management' },
            { text: 'GeoJSON 图层', link: '/guide/geojson-layer' },
            { text: 'WMS、TMS、WMTS 与单图影像', link: '/guide/imagery-layers' },
            { text: '密度热力图', link: '/guide/heatmap-layer' },
            { text: '3D Tiles 图层', link: '/guide/tiles3d-layer' },
            { text: '静态模型图层', link: '/guide/model-layer' },
            { text: '点位图层与 CSV 导入', link: '/guide/points-layer' },
            { text: '点位导入计划', link: '/guide/point-import' },
            { text: '折线图层与内置材质', link: '/guide/polyline-layer' },
            { text: '实时数据导航', link: '/guide/data-pipeline' },
            { text: '有界数据管线', link: '/guide/data-pipeline-core' },
            { text: 'Worker / MessagePort 输入', link: '/guide/data-pipeline-message-input' },
            { text: '帧预算调度', link: '/guide/data-pipeline-frame-scheduler' },
            { text: '实时链路（WebSocket）', link: '/guide/realtime-socket' },
            { text: '实时链路组装（从数据到画面）', link: '/guide/realtime-cookbook' },
            { text: '实时水位线与时间戳守卫', link: '/guide/realtime-waterline' },
            { text: '会话门禁与重同步', link: '/guide/realtime-session' },
            { text: '位置批量归一化', link: '/guide/position-batch' },
            { text: '仿真 / 回放时钟', link: '/guide/simulation-clock' },
            { text: '回放时间轴', link: '/guide/replay-timeline' },
            { text: '仿真事件调度', link: '/guide/simulation-events' },
            { text: '诊断快照', link: '/guide/diagnostics' },
            { text: '性能基准（计算与渲染）', link: '/guide/performance' },
            { text: '错误与原生出口', link: '/guide/errors-and-native' },
            { text: '功能状态与路线图', link: '/guide/capability-status' },
            { text: 'TypeScript 类型索引', link: '/api/' },
          ],
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/yanbobo-ONE/gis-sdk' }],
    search: { provider: 'local' },
    outline: { level: [2, 3], label: '本页内容' },
    docFooter: { prev: '上一页', next: '下一页' },
    lastUpdated: { text: '最后更新' },
  },
});
