/** SDK 可稳定判断的错误代码。 */
export type GisErrorCode =
  | 'ANALYSIS_ABORTED'
  | 'ANALYSIS_BATCH_FAILED'
  | 'ANALYSIS_TERRAIN_UNAVAILABLE'
  | 'ANALYSIS_WORKER_DISPOSED'
  | 'ANALYSIS_WORKER_QUEUE_FULL'
  | 'ANALYSIS_WORKER_FAILED'
  | 'ANALYSIS_WORKER_TIMEOUT'
  | 'BASEMAP_LOAD_FAILED'
  | 'CAMERA_FLIGHT_CANCELLED'
  | 'CAMERA_VIEW_UNAVAILABLE'
  | 'CESIUM_BASE_URL_CONFLICT'
  | 'CLOCK_TIME_UNAVAILABLE'
  | 'DATA_PIPELINE_CLOSED'
  | 'DATA_PIPELINE_FRAME_SCHEDULER_DISPOSED'
  | 'DATA_PIPELINE_FRAME_SCHEDULER_UNAVAILABLE'
  | 'DATA_PIPELINE_MESSAGE_ADAPTER_DISPOSED'
  | 'DUPLICATE_LAYER_ID'
  | 'ENVIRONMENT_UNSUPPORTED'
  | 'EVENT_LISTENER_FAILED'
  | 'INVALID_CONTAINER'
  | 'INVALID_CAMERA_VIEW'
  | 'INVALID_ANALYSIS_INPUT'
  | 'INVALID_COORDINATES'
  | 'INVALID_QUALITY_CONFIG'
  | 'INVALID_REPLAY_INPUT'
  | 'INVALID_REALTIME_CONFIG'
  | 'INVALID_REALTIME_SOCKET_CONFIG'
  | 'INVALID_REALTIME_INPUT'
  | 'INVALID_SCENE_CONFIG'
  | 'INVALID_CLOCK_CONFIG'
  | 'INVALID_PICKING_CONFIG'
  | 'INVALID_CRS_DEFINITION'
  | 'INVALID_CSV_INPUT'
  | 'INVALID_CZML'
  | 'INVALID_DRAWING_INPUT'
  | 'INVALID_ENVIRONMENT_CONFIG'
  | 'INVALID_FRAME_STATISTICS_CONFIG'
  | 'INVALID_SPATIAL_INPUT'
  | 'INVALID_BASEMAP_CONFIG'
  | 'INVALID_BASEMAP_OPACITY'
  | 'INVALID_DATA_PIPELINE_CONFIG'
  | 'INVALID_DATA_PIPELINE_FRAME_SCHEDULER_CONFIG'
  | 'INVALID_DATA_PIPELINE_KEY'
  | 'INVALID_DATA_PIPELINE_MESSAGE_ADAPTER_CONFIG'
  | 'INVALID_DATA_PIPELINE_TAKE_LIMIT'
  | 'INVALID_LAYER_ID'
  | 'INVALID_LAYER_STYLE'
  | 'INVALID_LAYER_COLOR'
  | 'INVALID_LAYER_CONFIG'
  | 'INVALID_LAYER_OPACITY'
  | 'INVALID_MODEL_LOAD_CONFIG'
  | 'INVALID_WMS_FILTER'
  | 'INVALID_WMS_PARAMETERS'
  | 'LAYER_BUSY'
  | 'LAYER_CLEAR_FAILED'
  | 'LAYER_DISPOSED'
  | 'LAYER_DISPOSE_FAILED'
  | 'LAYER_LOAD_FAILED'
  | 'LAYER_MANAGER_BUSY'
  | 'LAYER_MANAGER_DISPOSED'
  | 'LAYER_OPERATION_ABORTED'
  | 'MAP_DISPOSED'
  | 'MAP_DESTROY_FAILED'
  | 'INVALID_TERRAIN_CONFIG'
  | 'TERRAIN_BUSY'
  | 'TERRAIN_DISPOSED'
  | 'TERRAIN_LOAD_FAILED'
  | 'REALTIME_SOCKET_DISPOSED'
  | 'REALTIME_SOCKET_FAILED'
  | 'REALTIME_SOCKET_NOT_OPEN'
  | 'REALTIME_SOCKET_UNSUPPORTED'
  | 'TERRAIN_SAMPLING_ABORTED'
  | 'TERRAIN_SAMPLING_FAILED'
  | 'SCENE_MORPH_SUPERSEDED'
  | 'TERRAIN_SAMPLING_UNAVAILABLE'
  | 'UNKNOWN_ANALYSIS_TOOL'
  | 'UNSUPPORTED_CRS';
/**
 * 全部错误代码的运行时清单。
 *
 * 与 `GisErrorCode` 联合类型用 `satisfies` 双向锁定：漏写或多写都会在编译期报错。
 * 用于校验来自外部（Worker 消息、持久化数据、跨进程协议）的错误代码。
 */
export const GIS_ERROR_CODES = [
  'ANALYSIS_ABORTED',
  'ANALYSIS_BATCH_FAILED',
  'ANALYSIS_TERRAIN_UNAVAILABLE',
  'ANALYSIS_WORKER_DISPOSED',
  'ANALYSIS_WORKER_QUEUE_FULL',
  'ANALYSIS_WORKER_FAILED',
  'ANALYSIS_WORKER_TIMEOUT',
  'BASEMAP_LOAD_FAILED',
  'CAMERA_FLIGHT_CANCELLED',
  'CAMERA_VIEW_UNAVAILABLE',
  'CESIUM_BASE_URL_CONFLICT',
  'CLOCK_TIME_UNAVAILABLE',
  'DATA_PIPELINE_CLOSED',
  'DATA_PIPELINE_FRAME_SCHEDULER_DISPOSED',
  'DATA_PIPELINE_FRAME_SCHEDULER_UNAVAILABLE',
  'DATA_PIPELINE_MESSAGE_ADAPTER_DISPOSED',
  'DUPLICATE_LAYER_ID',
  'ENVIRONMENT_UNSUPPORTED',
  'EVENT_LISTENER_FAILED',
  'INVALID_CONTAINER',
  'INVALID_CAMERA_VIEW',
  'INVALID_ANALYSIS_INPUT',
  'INVALID_COORDINATES',
  'INVALID_QUALITY_CONFIG',
  'INVALID_REPLAY_INPUT',
  'INVALID_REALTIME_CONFIG',
  'INVALID_REALTIME_SOCKET_CONFIG',
  'INVALID_REALTIME_INPUT',
  'INVALID_SCENE_CONFIG',
  'INVALID_CLOCK_CONFIG',
  'INVALID_PICKING_CONFIG',
  'INVALID_CRS_DEFINITION',
  'INVALID_CSV_INPUT',
  'INVALID_CZML',
  'INVALID_DRAWING_INPUT',
  'INVALID_ENVIRONMENT_CONFIG',
  'INVALID_FRAME_STATISTICS_CONFIG',
  'INVALID_SPATIAL_INPUT',
  'INVALID_BASEMAP_CONFIG',
  'INVALID_BASEMAP_OPACITY',
  'INVALID_DATA_PIPELINE_CONFIG',
  'INVALID_DATA_PIPELINE_FRAME_SCHEDULER_CONFIG',
  'INVALID_DATA_PIPELINE_KEY',
  'INVALID_DATA_PIPELINE_MESSAGE_ADAPTER_CONFIG',
  'INVALID_DATA_PIPELINE_TAKE_LIMIT',
  'INVALID_LAYER_ID',
  'INVALID_LAYER_STYLE',
  'INVALID_LAYER_COLOR',
  'INVALID_LAYER_CONFIG',
  'INVALID_LAYER_OPACITY',
  'INVALID_MODEL_LOAD_CONFIG',
  'INVALID_WMS_FILTER',
  'INVALID_WMS_PARAMETERS',
  'LAYER_BUSY',
  'LAYER_CLEAR_FAILED',
  'LAYER_DISPOSED',
  'LAYER_DISPOSE_FAILED',
  'LAYER_LOAD_FAILED',
  'LAYER_MANAGER_BUSY',
  'LAYER_MANAGER_DISPOSED',
  'LAYER_OPERATION_ABORTED',
  'MAP_DISPOSED',
  'MAP_DESTROY_FAILED',
  'INVALID_TERRAIN_CONFIG',
  'TERRAIN_BUSY',
  'TERRAIN_DISPOSED',
  'TERRAIN_LOAD_FAILED',
  'REALTIME_SOCKET_DISPOSED',
  'REALTIME_SOCKET_FAILED',
  'REALTIME_SOCKET_NOT_OPEN',
  'REALTIME_SOCKET_UNSUPPORTED',
  'TERRAIN_SAMPLING_ABORTED',
  'TERRAIN_SAMPLING_FAILED',
  'SCENE_MORPH_SUPERSEDED',
  'TERRAIN_SAMPLING_UNAVAILABLE',
  'UNKNOWN_ANALYSIS_TOOL',
  'UNSUPPORTED_CRS',
] as const satisfies readonly GisErrorCode[];

type MissingErrorCodes = Exclude<GisErrorCode, (typeof GIS_ERROR_CODES)[number]>;
// 编译期穷尽性检查：漏写代码时下面这行会报 "not assignable to never"。
const ERROR_CODES_EXHAUSTIVE: MissingErrorCodes extends never ? true : never = true;
void ERROR_CODES_EXHAUSTIVE;

const GIS_ERROR_CODE_SET: ReadonlySet<string> = new Set<string>(GIS_ERROR_CODES);

/** 判断任意值是否为 SDK 已知的错误代码。 */
export function isGisErrorCode(value: unknown): value is GisErrorCode {
  return typeof value === 'string' && GIS_ERROR_CODE_SET.has(value);
}

/** 创建 {@link GisError} 所需的结构化上下文。 */
export interface GisErrorOptions {
  /** 稳定错误代码。 */
  readonly code: GisErrorCode;
  /** 发生错误的 SDK 模块。 */
  readonly module: string;
  /** 发生错误的具体操作。 */
  readonly operation: string;
  /** 调用方是否可以重试，默认 `false`。 */
  readonly retryable?: boolean;
  /** 原始异常或失败值。 */
  readonly cause?: unknown;
}

/** SDK 操作失败时抛出的结构化错误。 */
export class GisError extends Error {
  /** 供业务分支判断的稳定错误代码。 */
  readonly code: GisErrorCode;
  /** 发生错误的 SDK 模块。 */
  readonly module: string;
  /** 发生错误的具体操作。 */
  readonly operation: string;
  /** 当前操作是否允许由调用方重试。 */
  readonly retryable: boolean;

  /** 创建结构化 SDK 错误。 */
  constructor(message: string, options: GisErrorOptions) {
    super(message, { cause: options.cause });
    this.name = 'GisError';
    this.code = options.code;
    this.module = options.module;
    this.operation = options.operation;
    this.retryable = options.retryable ?? false;
  }
}
